export type InsumoBase = {
  nombre: string
  unidad: string
  categoria: string
  stock_minimo: number
}

export const INSUMOS_BASE_LA_FELICITTA: InsumoBase[] = [
  { nombre: 'Pollo entero', unidad: 'unidad', categoria: 'Carnes', stock_minimo: 4 },
  { nombre: 'Pollo desmechado', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Pollo para arroz chino', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Carne molida hamburguesa', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Carne mechada', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Carne churrasco', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Cerdo para arroz chino', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Cochino frito', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Pernil', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Chuleta ahumada', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Tocineta', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Chorizo', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Jamon', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Salchicha hot dog 15cm', unidad: 'unidad', categoria: 'Carnes', stock_minimo: 20 },
  { nombre: 'Salchicha hot dog 20cm', unidad: 'unidad', categoria: 'Carnes', stock_minimo: 20 },
  { nombre: 'Salchicha hot dog 22cm', unidad: 'unidad', categoria: 'Carnes', stock_minimo: 20 },
  { nombre: 'Nuggets', unidad: 'unidad', categoria: 'Carnes', stock_minimo: 24 },
  { nombre: 'Camaron', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Mariscos mixtos', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },

  { nombre: 'Pan brioche hamburguesa', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 20 },
  { nombre: 'Pan hot dog', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 20 },
  { nombre: 'Pan perro caliente', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 20 },
  { nombre: 'Pan completo', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 20 },
  { nombre: 'Pan completon', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 20 },
  { nombre: 'Pan churrasco grande', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 10 },
  { nombre: 'Pan churrasco normal', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 10 },
  { nombre: 'Pan churrasco pequeno', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 10 },
  { nombre: 'Pan pepito 15cm', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 10 },
  { nombre: 'Pan pepito XL', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 10 },
  { nombre: 'Pan pinita', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 4 },
  { nombre: 'Pan de guayaba', unidad: 'unidad', categoria: 'Panadería', stock_minimo: 4 },
  { nombre: 'Masa empanada', unidad: 'kg', categoria: 'Panadería', stock_minimo: 1 },
  { nombre: 'Masa tequeno', unidad: 'kg', categoria: 'Panadería', stock_minimo: 1 },
  { nombre: 'Masa churro', unidad: 'kg', categoria: 'Panadería', stock_minimo: 1 },
  { nombre: 'Mezcla cachapa', unidad: 'kg', categoria: 'Panadería', stock_minimo: 1 },
  { nombre: 'Harina de maiz', unidad: 'kg', categoria: 'Panadería', stock_minimo: 2 },
  { nombre: 'Harina de trigo', unidad: 'kg', categoria: 'Panadería', stock_minimo: 5 },
  { nombre: 'Levadura', unidad: 'kg', categoria: 'Panadería', stock_minimo: 0.2 },
  { nombre: 'Azucar', unidad: 'kg', categoria: 'Panadería', stock_minimo: 2 },
  { nombre: 'Sal', unidad: 'kg', categoria: 'Panadería', stock_minimo: 1 },
  { nombre: 'Mantequilla', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 1 },
  { nombre: 'Huevos', unidad: 'unidad', categoria: 'Otros', stock_minimo: 30 },

  { nombre: 'Queso gouda', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 1 },
  { nombre: 'Queso cheddar', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 1 },
  { nombre: 'Queso llanero', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 1 },
  { nombre: 'Queso de mano', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 1 },
  { nombre: 'Queso rallado', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 1 },
  { nombre: 'Queso para tequeno', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 2 },
  { nombre: 'Natilla', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 1 },
  { nombre: 'Leche', unidad: 'L', categoria: 'Lácteos', stock_minimo: 2 },
  { nombre: 'Leche condensada', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 1 },

  { nombre: 'Lechuga', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },
  { nombre: 'Tomate', unidad: 'kg', categoria: 'Verduras', stock_minimo: 2 },
  { nombre: 'Cebolla morada', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },
  { nombre: 'Cebolla normal', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },
  { nombre: 'Cebollin', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },
  { nombre: 'Repollo', unidad: 'kg', categoria: 'Verduras', stock_minimo: 2 },
  { nombre: 'Palta', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },
  { nombre: 'Poroto verde', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },
  { nombre: 'Aji verde', unidad: 'kg', categoria: 'Verduras', stock_minimo: 0.5 },
  { nombre: 'Diente de dragon', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },
  { nombre: 'Choclo', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },
  { nombre: 'Platano para tajadas', unidad: 'kg', categoria: 'Verduras', stock_minimo: 2 },
  { nombre: 'Platano para patacon', unidad: 'kg', categoria: 'Verduras', stock_minimo: 2 },
  { nombre: 'Caraotas', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },
  { nombre: 'Pepinillo', unidad: 'kg', categoria: 'Verduras', stock_minimo: 0.5 },

  { nombre: 'Papas prefritas', unidad: 'kg', categoria: 'Congelados', stock_minimo: 5 },
  { nombre: 'Papas hilo', unidad: 'kg', categoria: 'Otros', stock_minimo: 1 },
  { nombre: 'Arroz blanco', unidad: 'kg', categoria: 'Otros', stock_minimo: 5 },
  { nombre: 'Arroz chino preparado', unidad: 'kg', categoria: 'Otros', stock_minimo: 2 },
  { nombre: 'Aceite vegetal', unidad: 'L', categoria: 'Aceites', stock_minimo: 5 },
  { nombre: 'Ensalada mixta', unidad: 'kg', categoria: 'Verduras', stock_minimo: 1 },

  { nombre: 'Mayonesa casera', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Ketchup', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Mostaza', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Mayo ajo', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Salsa de la casa', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Salsa cheddar', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Salsa chocolate', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Salsa manjar', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Salsa guayaba', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Marinada pollo a la brasa', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Alino arroz chino', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Soya', unidad: 'L', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Ajo', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Oregano', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 0.2 },
  { nombre: 'Parmesano', unidad: 'kg', categoria: 'Lácteos', stock_minimo: 0.5 },
  { nombre: 'Azucar flor', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 1 },
  { nombre: 'Cebolla caramelizada', unidad: 'kg', categoria: 'Salsas y condimentos', stock_minimo: 0.5 },

  { nombre: 'Envase para llevar', unidad: 'unidad', categoria: 'Empaques', stock_minimo: 50 },
  { nombre: 'Bolsa papel', unidad: 'unidad', categoria: 'Empaques', stock_minimo: 50 },
  { nombre: 'Bolsa camiseta', unidad: 'unidad', categoria: 'Empaques', stock_minimo: 50 },
  { nombre: 'Servilletas', unidad: 'unidad', categoria: 'Empaques', stock_minimo: 100 },
  { nombre: 'Pote salsa', unidad: 'unidad', categoria: 'Empaques', stock_minimo: 50 },
  { nombre: 'Cubiertos', unidad: 'unidad', categoria: 'Empaques', stock_minimo: 50 },
  { nombre: 'Bombillas', unidad: 'unidad', categoria: 'Empaques', stock_minimo: 50 },
  { nombre: 'Vasos', unidad: 'unidad', categoria: 'Empaques', stock_minimo: 50 },

  { nombre: 'Coca-Cola 500cc', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 10 },
  { nombre: 'Coca-Cola lata', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 10 },
  { nombre: 'Sprite 500cc', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 10 },
  { nombre: 'Fanta 500cc', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 10 },
  { nombre: 'Bebida 1.5L', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 6 },
  { nombre: 'KR personal', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 10 },
  { nombre: 'Agua sin gas 500cc', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 10 },
  { nombre: 'Agua con gas 500cc', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 10 },
  { nombre: 'Naranja para jugo', unidad: 'kg', categoria: 'Bebidas', stock_minimo: 3 },
  { nombre: 'Pulpa mango', unidad: 'kg', categoria: 'Bebidas', stock_minimo: 1 },
  { nombre: 'Pulpa pina', unidad: 'kg', categoria: 'Bebidas', stock_minimo: 1 },
  { nombre: 'Pulpa maracuya', unidad: 'kg', categoria: 'Bebidas', stock_minimo: 1 },
  { nombre: 'Jugos Kris', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 10 },
  { nombre: 'Cafe', unidad: 'kg', categoria: 'Bebidas', stock_minimo: 0.5 },
  { nombre: 'Te infusiones', unidad: 'unidad', categoria: 'Bebidas', stock_minimo: 20 },
  { nombre: 'Chocolate caliente mezcla', unidad: 'kg', categoria: 'Bebidas', stock_minimo: 1 },

  { nombre: 'Chicharron', unidad: 'kg', categoria: 'Carnes', stock_minimo: 1 },
  { nombre: 'Perico', unidad: 'kg', categoria: 'Otros', stock_minimo: 1 },
  { nombre: 'Reina pepiada', unidad: 'kg', categoria: 'Otros', stock_minimo: 1 },
  { nombre: 'Bolitas pasapalo', unidad: 'unidad', categoria: 'Pasapalos', stock_minimo: 25 },
  { nombre: 'Pasteles pasapalo', unidad: 'unidad', categoria: 'Pasapalos', stock_minimo: 25 },
  { nombre: 'Mini pizzas pasapalo', unidad: 'unidad', categoria: 'Pasapalos', stock_minimo: 25 },
  { nombre: 'Mini empanadas pasapalo', unidad: 'unidad', categoria: 'Pasapalos', stock_minimo: 25 }
]
